name: scrape-and-publish
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */2 * * *"   # alle 2 Stunden automatisch
  workflow_dispatch: {}      # Button "Run workflow"
  push:                      # auch auslösen, wenn du diese Dateien änderst
    paths:
      - 'main.py'
      - 'requirements.txt'
      - '.github/workflows/run.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py

      - name: Commit & push signals
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/signals.json
          git commit -m "update signals" || echo "no changes"
          git push
